### ISSUE TITLE
/SegFormer/segformer.b5.1024x1024.city.160k.pth file not found

### ISSUE THREAD

**Issue by swagholikar29** [naitri/PointPainting#1]
above file mentioned in run instructions not found. Pl. suggest where to get the file to add to path.

**Comment by naitri** [comment]
Hello!
You can find more weights and details here : [Segformer](https://github.com/NVlabs/SegFormer
)
Pretrained details are given on the link above but here it is for reference : [Weights](https://drive.google.com/drive/folders/1GAku0G0iR9DsBxCbfENWMJ27c5lYUeQA)
